version: '3.3'

services:

  portainer:
    image: portainer/portainer
    ports:
      - '9000:9000'
    networks:
      - wms
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    links:
      - wordpress
      - db
      - phpmyadmin
    depends_on:
      - wordpress
      - db
      - phpmyadmin

  viz:
    image: dockersamples/visualizer
    ports:
      - '8888:8080'
    networks:
      - wms
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - db
      - wordpress
      - phpmyadmin

  wordpress:
    depends_on:
      - db
    image: max2wms/wms
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: Password_01
    ports:
      - 80:80
    networks:
      - wms

  db:
    image: mysql:5.7
    volumes:
      - ./data/actual/prod:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password_01
    networks:
      - wms

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8088:8080
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Password_01
    networks:
      - wms

networks:
  wms: