version: '3.3'

services:

  wordpress:
    container_name: wms_web
    depends_on:
      - db
    image: max2wms/wms
    build: .
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: Password_01
    ports:
      - 80:80
    networks:
      - wms

  db:
    container_name: wms_mysql
    image: mysql:5.7
    volumes:
      - ./data/actual/prod:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password_01
    networks:
      - wms

  phpmyadmin:
    container_name: wms_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8088:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Password_01
    networks:
      - wms

networks:
  wms: