version: '3.3'

services:

  wordpress:
    container_name: web
    depends_on:
      - db
    image: max2wms/wms
    build: .
    volumes:
      - ./web/wp-content:/var/www/html/wp-content
      - ./php.ini:/var/www/html/php.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: password01
    ports:
      - 80:80
    networks:
      - wms

  db:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./data/actual/dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password01
    networks:
      - wms

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password01
    networks:
      - wms

networks:
  wms: